# -*- coding: utf-8 -*-
"""
N1 聴解の音声を作る（edge-tts のみ。ffmpeg も pydub も要りません）

  n1_listening_manifest.json を読み、1問ずつ各行を音声にして
  audio/n1_qX_YY.mp3 に1本のmp3としてつなげます。

差分方式：
  audio/_n1_audio_sig.json に各問の台本＋声設定のハッシュを記録します。
  mp3が無い問題、台本を直した問題だけを作り直し、変わっていない問題は
  飛ばします。古いmp3を手で消す必要はありません。
  全部作り直したいときは、下の VOICE_VERSION を v2, v3 … と上げてください。

声：
  ナレーター（場面説明・設問）… 低め・ゆっくり（会話と区別するため）
  会話の女 … 標準よりやや高め
  会話の男 … 標準
  パートとパートの間に 0.6 秒の無音を挟みます。

使い方：
  make_n1_listening_audio.bat をダブルクリック
  （または python make_n1_listening_audio.py）
  できた audio フォルダを HTML と同じ場所に置いて、GitHub に上げてください。
"""
import os, sys, json, asyncio, tempfile, hashlib, base64

HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST = os.path.join(HERE, "n1_listening_manifest.json")
OUTDIR = os.path.join(HERE, "audio")
LOG = os.path.join(HERE, "_n1_listening_log.txt")
SIGFILE = os.path.join(OUTDIR, "_n1_audio_sig.json")

# 声の割り当てを変えたときは、ここを上げると全mp3が作り直されます。
VOICE_VERSION = "v1"

ROLE_VOICE = {"N": "ja-JP-NanamiNeural", "F": "ja-JP-NanamiNeural", "M": "ja-JP-KeitaNeural",
              "F2": "ja-JP-NanamiNeural", "M2": "ja-JP-KeitaNeural"}
ROLE_OPTS = {"N":  {"rate": "-10%", "pitch": "-16Hz"},   # ナレーター：低くゆっくり
             "F":  {"rate": "+3%",  "pitch": "+13Hz"},   # 会話の女
             "M":  {},                                    # 会話の男
             "F2": {"pitch": "+24Hz"},
             "M2": {"pitch": "-10Hz"}}

# 24kHz・モノラル・0.6秒の無音mp3（パート間の「間」に使う。ffmpeg不要）
SILENCE_B64 = ("SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//NkxAAAAANIAAAAAExBTUVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NkxHwAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV")
PAUSE_BYTES = base64.b64decode(SILENCE_B64)


def log(msg):
    print(msg)
    try:
        with open(LOG, "a", encoding="utf-8") as f:
            f.write(msg + "\n")
    except Exception:
        pass


def signature(it):
    h = hashlib.sha256()
    h.update(VOICE_VERSION.encode("utf-8"))
    h.update(b"pause0.6")
    for seg in it["segments"]:
        role = seg["role"]
        voice = ROLE_VOICE.get(role, "ja-JP-NanamiNeural")
        opts = ROLE_OPTS.get(role, {})
        h.update(("\x1f".join([role, seg["text"], voice, json.dumps(opts, sort_keys=True)]) + "\x1e").encode("utf-8"))
    return h.hexdigest()


async def synth(text, voice, opts, out):
    import edge_tts
    await edge_tts.Communicate(text, voice, **opts).save(out)


def main():
    try:
        import edge_tts  # noqa
    except ImportError:
        log("[エラー] edge-tts が入っていません。コマンドプロンプトで次を実行してください：")
        log("         pip install edge-tts")
        sys.exit(1)
    if not os.path.exists(MANIFEST):
        log("[エラー] n1_listening_manifest.json がこのスクリプトと同じ場所にありません。")
        sys.exit(1)

    man = json.load(open(MANIFEST, encoding="utf-8"))
    items = man["items"]
    os.makedirs(OUTDIR, exist_ok=True)
    open(LOG, "w", encoding="utf-8").close()
    log("問題数 = %d" % len(items))

    try:
        sigs = json.load(open(SIGFILE, encoding="utf-8"))
        if not isinstance(sigs, dict):
            sigs = {}
    except Exception:
        sigs = {}

    made = updated = skipped = failed = 0
    for idx, it in enumerate(items, 1):
        fname = it["file"]
        out = os.path.join(OUTDIR, fname)
        sig = signature(it)
        exists = os.path.exists(out) and os.path.getsize(out) > 0
        rec = sigs.get(fname)
        if exists and (rec is None or rec == sig):
            if rec is None:
                sigs[fname] = sig
            skipped += 1
            continue
        reason = "新規" if not exists else "作り直し"
        try:
            parts = []
            for si, seg in enumerate(it["segments"]):
                role = seg["role"]
                voice = ROLE_VOICE.get(role, "ja-JP-NanamiNeural")
                opts = ROLE_OPTS.get(role, {})
                tmp = tempfile.mktemp(suffix=".mp3")
                asyncio.run(synth(seg["text"], voice, opts, tmp))
                with open(tmp, "rb") as f:
                    parts.append(f.read())
                try:
                    os.remove(tmp)
                except Exception:
                    pass
                if si != len(it["segments"]) - 1:
                    parts.append(PAUSE_BYTES)   # パート間の無音
            with open(out, "wb") as f:
                f.write(b"".join(parts))
            sigs[fname] = sig
            if reason == "新規":
                made += 1
            else:
                updated += 1
            log("[OK] %2d/%d  %s  (%d行, %s)" % (idx, len(items), fname, len(it["segments"]), reason))
        except Exception as e:
            failed += 1
            log("[NG] %s  (%s)" % (fname, e))

    try:
        json.dump(sigs, open(SIGFILE, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
    except Exception as e:
        log("[警告] 署名ファイルを書けませんでした: %s" % e)

    log("---- 完了：新規 %d / 作り直し %d / 変更なし %d / 失敗 %d ----" % (made, updated, skipped, failed))
    log("audio フォルダを HTML と同じ場所に置いて、GitHub に上げてください。")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
